### ISSUE TITLE
always set InputXML when you parse the file.

### ISSUE THREAD

**Issue by benpallen** [jaerith/ONIX-Data#1]
Hi,

You only setInputXML if there is an exception in MoveNext method. 
(
https://github.com/jaerith/ONIX-Data/blob/master/OnixData/OnixLegacyPlusParser.cs - line 242
and
https://github.com/jaerith/ONIX-Data/blob/master/OnixData/OnixLegacyParser.cs - line 588.
)
Can you set InputXML if you don't get an exception too?

Thanks

**Comment by jaerith** [comment]
Of course, that could be done.  Out of curiosity, though, why would you want that?  Mainly, I saw the input XML as useful only when trying to diagnose an issue with the XML (improper data, etc.).

**Comment by benpallen** [comment]
It is very helpful to get the XML of a title on the development phase of an application to compare the original XML file with your own object.
It is not a big deal, I can make those little changes after downloading the library but I think it would be helpful to have that features especially for people that use your library.

Thank you very much for your work and the library is very helpful.

**Comment by jaerith** [comment]
Ah, I see.  Perfectly understandable.
I went ahead and added an AlwaysReturnInputXml property to the LegacyParser.  It will control whether or not the record's XML will be returned with the record.

Thanks for the kind words about the project!  I'm glad that it benefits someone other than me.

**Comment by benpallen** [comment]
Thanks for the update.
There is one little problem.
You set the inputxml before creating the CurrentRecord instance and I get exception.

**Comment by jaerith** [comment]
Whoops!  It's kinda important to actually test a change, isn't it?  :smile: 

Okay, I went ahead, fixed it, AND tested it.  Let me know if it works for you.

**Comment by benpallen** [comment]
Thank you for the update
