### ISSUE TITLE
Extending project with GitHub Actions (CI)

### ISSUE THREAD

**Issue by szolkowski** [jaerith/ONIX-Data#19]
Hello,

I wanted to learn GitHub Actions and used my fork of this project as playground. I think it can be also added to main project since it is always good to have CI working for projects. I prepared them just for NETStandard part, since it is where tests are.

You can take a look how it looks like I my fork:

https://github.com/Stanislaw000/ONIX-Data/actions

PR: https://github.com/Stanislaw000/ONIX-Data/pull/6 (you need to click on show details box).

![image](https://user-images.githubusercontent.com/44289106/127845602-3faef66e-9807-441b-a968-104441688139.png)

Tests results: https://github.com/Stanislaw000/ONIX-Data/runs/3182479870?check_suite_focus=true

Workflow files are in pull request #18 

If you prefer to change something or customize let me know, so we can improve this solution.

**Comment by jaerith** [comment]
Good idea!  I had also planned on checking those out at some point.  Looks like you're way ahead of me.  :)

**Comment by jaerith** [comment]
Question: Is the "Test Report" being run twice, once at the end of the CI step (i.e., at the bottom of ci.yml) and then as a trigger once the CI step completes (i.e., test-report.yml)?

**Comment by szolkowski** [comment]
It isn't - it will be run on default branch only( I am assuming this, since I didn't want to mess up my fork by switching default branches between master and NetStandard). I was using recommended setup for public repository based on "Test reporter" action recommendation: https://github.com/dorny/test-reporter
