### ISSUE TITLE
Legacy Plus Parser crashes at "MoveNext"

### ISSUE THREAD

**Issue by rlee-uls** [jaerith/ONIX-Data#27]
Hello,

When an error occurs during the MoveNext function in the Legacy Plus Parser, the reading of the file stops completely.
In the Legacy Parser, it does not do that.

Legacy Plus MoveNext does not return a true on the bResult when this happens.  
It doesn't do that in the Legacy unless the # of products count is finished.

Thank you.

**Comment by jaerith** [comment]
Good catch, @ordio!  That is definitely a bug.  Whoops!

A fix was put into place.  Fortunately, that was an easy one to repair.  :)

Thanks again!
