### ISSUE TITLE
Determine Onix file version

### ISSUE THREAD

**Issue by rlee-uls** [jaerith/ONIX-Data#5]
Hi Jaerith,

Thank you again for making the time for the issue I had with the Default header price type codes.  I appreciate it a lot.

I was wondering (when you have time) if there was a way to determine which ONIX version was sent to us.

Thank you!

**Comment by jaerith** [comment]
Hi Ordio,

I've updated the code with two simple extension methods, IsOnixFile() and IsOnixVersion3File().  Nothing fancy, but it should get the job done.  Tell me if they work for you.

**Comment by rlee-uls** [comment]
Hi Jaerith,

Thank you for the updated code.  I really appreciate it.

I was wondering if you could show me an example on how to use the extension?

Thanks!

**Comment by rlee-uls** [comment]
Ha nevermind... i figured it out.

For anyone that isn't sure... maybe others have a better way to do it than I do.

    Public Function GetOnixVersion(strFile As String) As String
        'Return values of blank, 2.1 or 3.0
        Dim sOnixVersion As String = "2.1"

        Dim CurrentFileInfo As New FileInfo(strFile)
        'Assume 2.1 for now...

        Try
            WriteToLog("GetOnixVersion Testing for v3.0 of " & strFile)
            If OnixData.Extensions.OnixParserExtensions.IsOnixVersion3File(CurrentFileInfo) Then
                sOnixVersion = "3.0"
            End If
        Catch ex As Exception
            WriteToLog("GetOnixVersion Testing for v3.0 of " & strFile & " failed due to exception.")
            WriteToLog(ex.ToString())
        End Try

        CurrentFileInfo = Nothing
        WriteToLog("GetOnixVersion Version " & sOnixVersion & " found.")
        Return sOnixVersion
    End Function

Thanks again!

**Comment by jaerith** [comment]
Since it's an extension, you can also just call the method via the FileInfo object, in a C# version of your example (since I haven't written VB in a long time):

```
public string GetOnixVersion(string strFile)
{
    var CurrentFileInfo = new FileInfo(strFile);

    return CurrentFileInfo.IsOnixVersion3File() ? "3.0" : "2.1";
}
```

**Comment by rlee-uls** [comment]
I must not have it connected to the FileInfo object properly.  

I tried to even see if any of the new methods pop up (CurrentFileInfo. )  and the popup doesn't show any of the new methods.

Thanks for the help!!

**Comment by jaerith** [comment]
And there is a mention of "Imports OnixData.Extensions" at the top of your module?

**Comment by jaerith** [comment]
Whoops, my mistake: they were not actually extension methods.  I went ahead and fixed that.

As long as you're importing OnixData.Extensions in the same module as your function, you should now be able to use something similar to my example.

**Comment by rlee-uls** [comment]
Ahh of course... Forgot the Imports!  

Thank you for the update.  Its all working great now!

Appreciate this!
