### ISSUE TITLE
OnixLegacyPlusParser skipping every 2nd record

### ISSUE THREAD

**Issue by rlee-uls** [jaerith/ONIX-Data#7]
Hi there,

The OnixLegacyPlusParser (haven't tried this with OnixPlusParser) is skipping every 2nd record when the file doesn't have line separators. 

When there are line separators between fields, it works fine.

**Comment by jaerith** [comment]
Good find!  It's been fixed now.

**Comment by rlee-uls** [comment]
> Good find! It's been fixed now.

Thank you!
