### ISSUE TITLE
Missing Price.Territory.CountriesIncluded

### ISSUE THREAD

**Issue by dgil-unedbarbastro** [jaerith/ONIX-Data#9]
Hi,

I'm trying to filter the price list by country using the  field `Territory.CountriesIncluded`:

![image](https://user-images.githubusercontent.com/78791313/121527174-6b0db700-c9fa-11eb-9ba6-0729f93eaa8f.png)

but I'm not able to find it. 

When I inspect the `OnixData.Version3.Price.OnixPrice` object and I can't find it:

![image](https://user-images.githubusercontent.com/78791313/121527081-516c6f80-c9fa-11eb-87d2-f9f745496f36.png)

Am I searching in the wrong place?

Regards,
Dani

**Comment by jaerith** [comment]
Hi Dani!  Yes, currently that tag is not yet supported by the parser, but it's easy enough to implement.  I'll try to do so in the near future.

FYI - this project supports many tags within the ONIX standard, but it doesn't yet support all of them.  The scope and complexity of ONIX 3.0 is a bit overwhelming at times.

**Comment by jaerith** [comment]
I added Territory as a property of the Price composite.  Let me know if it works for you!

**Comment by dgil-unedbarbastro** [comment]
Thanks @jaerith works great. 

I was using your nuget ONIX-Data (`v0.5.0`) from the `Nuget Package Manager`, and for this test I've cloned your repo and I've added the OnixData project to my solution as existing project. Will you update the nuget?

**Comment by jaerith** [comment]
Actually, the package was overdue for an update.  [The new version 0.5.1](https://www.nuget.org/packages/ONIX-Data/0.5.1) is now available.
